### PR TITLE
Updated Xamarin.Forms to 2.0

### PR DESCRIPTION
**Pull request by mrbelk**
I updated the references to Xamarin.Forms to 2.0.0.6490, updated the Xamarin.SignaturePad component, and created a very simple test harness app that doesn't depend on any external nugets except Acr.UserDialogs.

I also updated the .nuspec package version and dependencies.

### CODE REVIEW

**Comment by vcastellano-spl** [comment]
Tested and using these until there is an official release. Have had no issues.

**Comment by percramer** [comment]
I tried this one, seems to work. But after i have finished a signature my stack is closed and i drop down to the main page. If i remove the code for it then it works normal again. Any ideas?

**Comment by jmro20** [comment]
@mrbelk Did you get this to work? Will you share a working example?

Thanks!

**Comment by mrbelk** [comment]
@jmro20 What do you mean by a working example?

**Comment by jmro20** [comment]
I couldn't get it to run the samples but I compiled the dlls and added to my projects and it's working.

Thanks!

Sent from Outlook Mobile

On Wed, Mar 30, 2016 at 9:44 AM -0700, "Matthew Belk" notifications@github.com wrote:

@jmro20 What do you mean by a working example?

---

**Pull request closed without merging**
