### PR TITLE
added Text property to PromptConfig for initial input, use it in Android...

### PR DESCRIPTION
**Pull request by gabornemeth**
... UserDialogService
Could not implement and test on iOS and WindowsPhone.
If you don't pull this, even then it would be useful to implement such feature.

### CODE REVIEW

**Comment by aritchie** [comment]
Hi @gabornemeth 
I appreciate the PR, but I don't really agree with stuffing text in a prompt dialog.  I don't believe prompts should be used in an edit fashion because they are hard to move around in.  Prompts should be used for quick text grabs from a user

**Comment by gabornemeth** [comment]
Hi @aritchie 
How would you achieve the following? For example the user wants to download a file, and you'd like to provide a default filename, which she can modify. Just a simple input is required, but it's quite uncomfortable to input a longer name from scratch. A complete page is overkill for this, I think. You can leave Text null (as it is by default), and have a flexible solution.

**Comment by aritchie** [comment]
@gabornemeth alright, your use-case seems pretty straight forward.  I'm not going to take this PR because it is incomplete, but I will look to add it to the new user dialog library  -https://github.com/aritchie/userdialogs

I'll close this once it is complete

**Comment by aritchie** [comment]
https://www.nuget.org/packages/Acr.UserDialogs/ is the new library that contains this request.  I also added the ability to make it so you cannot cancel a prompt which should be beneficial to your use-case

**Pull request closed without merging**
